
package Biseccion;

import static Biseccion.Biseccion.F;
import static Biseccion.Biseccion.hayRaiz;
import static Biseccion.Biseccion.sacarK;
import static Biseccion.Biseccion.sacarRaiz;

/**
 *
 * @author Martín
 */
public class MainPanel extends javax.swing.JPanel {

    /**
     * Creates new form MainPanel
     */
    public MainPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCalcular = new javax.swing.JButton();
        cbOperacion = new javax.swing.JComboBox<>();
        lbValorA = new javax.swing.JTextField();
        lbValorB = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbResultado = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lbValorC = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        btnCalcular.setText("Calcular");
        btnCalcular.setToolTipText("");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        cbOperacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Epsilon", "Veces de Repeticion" }));

        lbValorA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbValorAActionPerformed(evt);
            }
        });

        lbValorB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbValorBActionPerformed(evt);
            }
        });

        jLabel1.setText("Valor de A:");

        jLabel2.setText("Valor de B:");

        jLabel3.setText("Ingrese el valor:");

        jLabel4.setText("Valor de x");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(201, 201, 201)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(lbValorC, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnCalcular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(lbResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(216, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbValorA))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbValorB, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(150, 150, 150))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbValorA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbValorB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addComponent(cbOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(lbValorC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCalcular)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(92, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        String textoA = lbValorA.getText();
        String textoB = lbValorB.getText();
        String repeticion = lbValorC.getText();
        double datoA = 0, datoB = 0, datoC = 0, x = 0;
        try{
            datoA = Double.valueOf(textoA);
            datoB = Double.valueOf(textoB);
            datoC = Double.valueOf(repeticion);
        }
        catch(NumberFormatException e){
            System.out.println("Error: " + e);
        }
        
        int operacion = cbOperacion.getSelectedIndex();
        switch(operacion){
            case 0: //Epsilon
                if (F(datoA) * F(datoB) == 0){
                System.out.println("Hay raiz");
                    if (F(datoA) == 0) {
                        System.out.println("Respuesta:" + textoA);
                    } else {
                        System.out.println("Respuesta:" + textoB);
                    }
                }else{
                    boolean siHayRaiz = hayRaiz(datoA,datoB);
                    if (siHayRaiz == true){
                        int k = sacarK(datoA, datoB, datoC);
                        x = sacarRaiz(datoA,datoB,k);
                    }else{ 
                    //something
                    }
                } 
                break;
            case 1: //Intervalo
                if (F(datoA) * F(datoB) == 0){
                System.out.println("Hay raiz");
                    if (F(datoA) == 0) {
                        System.out.println("Respuesta:" + textoA);
                    } else {
                        System.out.println("Respuesta:" + textoB);
                    }
                }else{
                    boolean siHayRaiz = hayRaiz(datoA,datoB);
                    if (siHayRaiz == true){
                        int k = (int) datoC;
                        x = sacarRaiz(datoA,datoB,k);
                    }else{ 
                    //something
                    }
                } 
        }
        
        StringBuilder builder = new StringBuilder();
        builder.append(x);
        lbResultado.setText(builder.toString());


    }//GEN-LAST:event_btnCalcularActionPerformed

    private void lbValorBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbValorBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbValorBActionPerformed

    private void lbValorAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbValorAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbValorAActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JComboBox<String> cbOperacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField lbResultado;
    private javax.swing.JTextField lbValorA;
    private javax.swing.JTextField lbValorB;
    private javax.swing.JTextField lbValorC;
    // End of variables declaration//GEN-END:variables
}
